version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - containedctx
    - depguard
    - dupl
    - dupword
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - interfacebloat
    - ireturn
    - lll
    - nilnil
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    misspell:
      ignore-rules:
        - tiem # dublikātiem "misspelled" "time" as "tiem"
    nlreturn:
      block-size: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: the type name `ErrorResponse` should conform to the `XxxError` format
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
